### ISSUE TITLE
Python APIs that must be preceeded by GravityNode.init() should check for it

### ISSUE THREAD

**Issue by bill-wright** [aphysci/gravity#149]
This code causes the python interpreter to segfault:

```python
    from gravity import GravityNode
    gn = GravityNode()
    model_file = gn.getStringParam("model_file", "model.json")
```
On Ubuntu 18.04.4 Python 3.6.9

**Comment by mbarger99** [comment]
It's actually the underlying C++ API that has the issue - it crashes too in the same circumstances.  Regardless this should be addressed.

**Comment by mbarger99** [comment]
I went through and ensured that that several calls return an error if the GravityNode has not been initialized.  The getXXXParam calls now return the provided default value in this case since there's not a way to return an error code via the current API.  A forthcoming issue will look at potentially changing how initialization works here.
 
Fix is now merged in.
