### ISSUE TITLE
Allow for debug flag in cpp build.

### ISSUE THREAD

**Issue by CptanPanic** [aphysci/gravity#17]
So I have tried using 'export CFLAGS='-g -O0' to enable debug symbols before runing configure, and this adds this flag to the library compile, but not the objects themselves.  Can you add $(AC_FLAGS) to make @$(CC) $(COUTPUT_FLAG)$@ $(COMPILE_FLAG) $(CFLAGS) $(AC_CFLAGS) $< in gravity/src/api/cpp/Makefile

**Comment by mbarger99** [comment]
Thanks for opening this @CptanPanic, it really needs to be fixed.

**Comment by mbarger99** [comment]
The fix is checked in and submitted under PR #89.  

Note that the fix changes the default build settings for the gravity lib, java and python wrapper libs and the c++components (ServiceDirectory, FileArchiver, etc).  These source files will now be compiled with -g -O2 by default.  You can override this by setting CFLAGS in your environment 
(e.g. export CFLAGS="-O3").
