### ISSUE TITLE
Python binding wrongly de-allocates handler on unsubscribe()

### ISSUE THREAD

**Issue by chrismurf** [aphysci/gravity#52]
It seems like the C++ object is being (wrongly) deallocated on unsubscribe, which causes all sorts of issues on the Python side.  Example:

```python
#!/usr/bin/env python
import time
import gravity

class Handler(gravity.GravitySubscriber):
    def subscriptionFilled(self, dataProducts):
        pass

handler = Handler()
node = gravity.GravityNode()
node.init("SegFaultCity")
node.subscribe("SegFaultsRUs", handler)

while True:
    print handler, type(handler)
    time.sleep(0.1)
    node.unsubscribe("SegFaultsRUs", handler)
```

The results when running it vary:
```python
<__main__.Handler; proxy of <Swig Object of type 'gravity::GravitySubscriber *' at 0x7f9c253cfa20> > <class '__main__.Handler'>
<__main__.Handler; proxy of <Swig Object of type 'gravity::GravitySubscriber *' at 0x7f9c253cfa20> > <class '__main__.Handler'>
<__main__.Handler;  > <class '__main__.Handler'>
Segmentation fault
```

or 

```python 
<__main__.Handler; proxy of <Swig Object of type 'gravity::GravitySubscriber *' at 0x7f502462a9c0> > <class '__main__.Handler'>
<__main__.Handler; proxy of <Swig Object of type 'gravity::GravitySubscriber *' at 0x7f502462a9c0> > <class '__main__.Handler'>
Fatal Python error: Inconsistent interned string state.
Aborted
```

I also managed to have handler get interpreted as `<listiterator at 0x7fbb14093f50>` and `(<sqlite3.Connection at 0x7fbb17831dc8>,)` which are some pretty creative options.

**Comment by mbarger99** [comment]
The problem is that the call to unsubscribe is decrementing the refcount on that handler each time it's called, but it's not checking to ensure that it doesn't decrement more than it added in the first place on the subscribe calls.

Or are you seeing that this issue occurs even in cases where unsubscribe is called no more often than subscribe is called on the same handler?  I wasn't able to reproduce this in that case.

In either case it's still a bug, but a more egregious one if this is potentially corrupting memory every time unsubscribe is called.

**Comment by mbarger99** [comment]
Agreed - it's still a bug.  I just wanted to make sure I understood the circumstances that trigger it.
